accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'


urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout, name='logout'),
]

articles/urls.py
from django.urls import path
from . import views


app_name = "articles"


urlpatterns = [
    path('',views.index,name='index'),
    path('create/',views.create,name='create'),
    path('<int:id>/detail/',views.detail,name='detail'),
    path('<int:article_id>/comments/create/',views.comment_create, name='comment_create'),
]

auth/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('articles/',include('articles.urls')),

    
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.



class User(AbstractUser):
    pass

articles/models.py
from django.db import models
from accounts.models import User 
from django.contrib.auth import get_user_model

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    user = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)


class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article,on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from .models import User


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields


class CustomAuthenticationForm(AuthenticationForm):
    pass

articles/forms.py
from django import forms
from .models import Article, Comment




class AritcleForm(forms.ModelForm):
    class Meta():
        model = Article
        exclude = ('user',)


class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('content',)

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()

    context = {
        'form': form,
    }

    return render(request,'signup.html',context)


def login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())

            next_url = request.GET.get('next')

            return redirect(next_url or 'articles:index')

    else:
        form = CustomAuthenticationForm()
    context = {
        'form': form,
    }
    return render(request,'login.html',context)

def logout(request):
    auth_logout(request)

    return redirect('articles:index')
    

articles/views.py
from django.shortcuts import render,redirect
from .forms import AritcleForm, CommentForm
from .models import Article, Comment
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    articles = Article.objects.all()

    context = {
        'articles': articles,
    }

    return render(request, 'index.html',context)

@login_required
def create(request):
    if request.method == 'POST':
        form = AritcleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:index')
    else:
        form = AritcleForm()

    context = {
        'form': form,
    }
    return render (request,'form.html',context)

def detail(request,id):
    article = Article.objects.get(id=id)

    context = {
        'article': article,
    }
    return render(request,'detail.html',context)


def comment_create(request,article_id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user.id = request.user.id
            comment.article.id = article_id
            comment.save()
            return redirect('articles:detail', id=article_id)
    else:
        form = CommentForm()
    
    context = {
        'form': form,
    }

    return redirect('articles:detail',id=article_id)

accounts/templates/login.html
{% extends 'base.html' %} 



{% block body %}

<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>

{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}



{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}

        <input type="submit">
    </form>
    
{% endblock %}

articles/templates/detail.html
{% extends 'base.html' %}



{% block body %}
    
    

    <h3>{{article.title}}</h3>
    <h5>{{article.user}}</h5>
    <hr>
    <p>{{article.content}}</p>

    <form action="" method ="POST">
        {{form}}
        <input type="submit">
    </form>

    <hr>

    {% for comment in article.commnet_set.all %}
        <p>{{comment.user}} : {{comment.content}}</p>

    {% endfor %}

{% endblock %}

articles/templates/form.html
{% extends 'base.html' %}



{% block body %}
<form action="" method="POST">
    {% csrf_token %}
    {{form}}

    <input type="submit">
</form>



{% endblock %}

articles/templates/index.html
{% extends 'base.html' %}



{% block body %}
{% for article in articles %}
    <h5>{{article.title}}</h5>
    <p>{{article.user}}</p>
    <a href="{% url 'articles:detail' id=article.id %}">detail</a>
    <hr>
{% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'articles:index' %}">HOME</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">

            {% if not user.is_authenticated %}        
              <a class="nav-link active" aria-current="page" href="{% url 'accounts:signup' %}">signup</a>
              <a class="nav-link" href="{% url 'accounts:login' %}">login</a>
            {% else %}    
              <a class="nav-link" href="{% url 'accounts:logout' %}">logout</a>
              <a class="nav-link disabled" aria-disabled="true">{{user}}</a>
              <a class = "nav-link" href="{% url 'articles:create' %}">Create</a>
            {% endif %}
            </div>
          </div>
        </div>
    </nav>

    <div class="container">
        {% block body %}
        {% endblock %} 
    </div>

 
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>